apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: diner-server
        image: diner-server:v1  # Specify your API service Docker image
        envFrom:
         - configMapRef:
             name: dinerconfigmap
        ports:
        - containerPort: 4000  # Adjust if your API service listens on a different port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
