apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  selector:
    app: controller
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 # Port your backend app listens on
  type: NodePort
