name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_REGISTRY_TOKEN }}

    # Build and Push Docker image for each service
    - name: Build and Push Docker image for Controller
      uses: docker/build-push-action@v2
      with:
        context: ./apps/controller
        file: ./apps/controller/Dockerfile
        push: true
        tags: registry.digitalocean.com/humidresearch/controller:${{ github.sha }}

    - name: Build and Push Docker image for Server
      uses: docker/build-push-action@v2
      with:
        context: ./apps/server
        file: ./apps/server/Dockerfile
        push: true
        tags: registry.digitalocean.com/humidresearch/server:${{ github.sha }}

    - name: Build and Push Docker image for Watcher
      uses: docker/build-push-action@v2
      with:
        context: ./apps/watcher
        file: ./apps/watcher/Dockerfile
        push: true
        tags: registry.digitalocean.com/humidresearch/watcher:${{ github.sha }}

    - name: Build and Push Docker image for Web
      uses: docker/build-push-action@v2
      with:
        context: ./apps/web
        file: ./apps/web/Dockerfile
        push: true
        tags: registry.digitalocean.com/humidresearch/web:${{ github.sha }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save your-cluster-name

    # Update Kubernetes deployment for each service
    - name: Update Kubernetes deployment for Controller
      run: |
        kubectl set image deployment/controller-deployment controller=registry.digitalocean.com/humidresearch/controller:${{ github.sha }} --record

    - name: Update Kubernetes deployment for Server
      run: |
        kubectl set image deployment/server-deployment server=registry.digitalocean.com/humidresearch/server:${{ github.sha }} --record

    - name: Update Kubernetes deployment for Watcher
      run: |
        kubectl set image deployment/watcher-deployment watcher=registry.digitalocean.com/humidresearch/watcher:${{ github.sha }} --record

    - name: Update Kubernetes deployment for Web
      run: |
        kubectl set image deployment/web-deployment web=registry.digitalocean.com/humidresearch/web:${{ github.sha }} --record
