name: Registry Garbage Collection

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  garbage-collect:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Delete Untagged Images
      run: |
        REPO_NAME="humidresearch"  # Replace with your actual repository name
        # Fetch the list of digests for untagged images
        TAGS=$(doctl registry repository list-manifests $REPO_NAME --format Tags --no-header)
        # Loop through and delete each untagged image
        # for TAG in $TAGS; do
        #   if [[ $TAG == "<none>" ]]; then
        #   doctl registry repository delete-manifest $REPO_NAME --digest "$DIGEST" --force
        # done
        echo $TAGS
      shell: bash

    # - name: Garbage Collect Registry
    #   run: doctl registry garbage-collection start --include-untagged-manifests humidresearch --force
    
      
    